### PR TITLE
Add locations easier

### PR DESCRIPTION
**Pull request by RedSparr0w**
#### Page to add locations to configuration quicker.

Note: you will need a google maps API key to use this.
Insert it on line 7

``` html
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&key=YOUR_KEY_HERE"></script>
```
### How to use:

`Right Click` -> `Add Marker`,
Once All markers for a area are on the map:
`Right Click` -> `Copy Marker Locations`
paste into 
configuration.json 
- Regions 
  -  Locations
### Output:

``` json
[
    {
        "Latitude": 40.78408342593807,
        "Longitude": -73.96944522857666
    },
    {
        "Latitude": 40.78388845869956,
        "Longitude": -73.96820068359375
    },
    {
        "Latitude": 40.78333604841566,
        "Longitude": -73.96734237670898
    },
    {
        "Latitude": 40.78284862376137,
        "Longitude": -73.96734237670898
    }
]
```

### CODE REVIEW

**Comment by bunzosteele** [comment]
Oh awesome, I was just starting to write a console app to do something similar! Thanks!

**Comment by RedSparr0w** [comment]
No Problem [=,

Will change to circles once we know the radius, so you can see how much area is covered/missed.

Edit: Also Something may need to be put in the README about how to use

**Comment by bunzosteele** [comment]
Yeah I'll update the readme shortly, or you can add a write up if you like. I'm using it now and it seems great. Also, radius did get hit, its down to 70 meters :(

**Comment by bunzosteele** [comment]
Would love a way to remove points without refreshing and clearing everyting

**Comment by RedSparr0w** [comment]
Will be the next thing I add, probably going to make it able to do multiple locations at once as well without reloading/removing pins.

Sent from my iPhone

On 30/07/2016, at 4:37 PM, bunzosteele <notifications@github.com<mailto:notifications@github.com>> wrote:

Would love a way to remove points without refreshing and clearing everyting

##

**Comment by JL907** [comment]
Are we still going to have kml support

**Comment by bunzosteele** [comment]
If this has the ability to load custom maps, then it would be pretty redundant, but I'm not sure if you can customize the maps url

**Pull request merged**
