### PR TITLE
Updated configGenerator to work when run from local file system

### PR DESCRIPTION
**Pull request by RedSparr0w**
Should be working now, was testing on web server so some of the stuff wasn't loading when launched from local disk.

Updated Script Urls to http:// instead of // as was trying to find files on file://
Moved `Configuration.json` into localstorage as was unable to get the file from local file system
### To fill large area with markers:
- Right click map
- Click "Mass Marker Area"
- Resize/Move Rectangle to required area
- Right click on rectangle
- Choose location to attribute markers to

autofill more efficient now:
markers
map
### Still a few things to do:
- [ ] add search for address/area
- [x] remember previous location to return to on page reload
- [ ] add ability to remove markers/circles
- [ ] add ability to swap "area" for markers/circles
- [x] add ability to import current config
- [x] mark current locations already in config on the map
- [x] update colors of markers when locations removed
- [ ] add Exclude/regularTweet/priorityTweet pokemon list
- [x] add custom hashtags
- [x] add rate limit
- [ ] add minimum life expectancy
- [ ] add pokemon name overides

### CODE REVIEW

**Comment by bunzosteele** [comment]
Looks really good! I'll test it out when I get the chance then merge

**Comment by ibobotastic** [comment]
Config file only downloads when no markers are set

**Comment by RedSparr0w** [comment]
Just about to push an update and that should be fixed =]

Sent from my iPhone

On 1/08/2016, at 1:01 PM, ibobotastic <notifications@github.com<mailto:notifications@github.com>> wrote:

Config file only downloads when no markers are set

##

**Comment by RedSparr0w** [comment]
Hmm, it seems deppending where in the world you are the mass area generator may not be as effective as it should be.

New Zealand:


Bellingham:


New York:

**Comment by bunzosteele** [comment]
Lat and Long values -> Meters change slightly depending on where in the world you are, so making an assumption of .002 long = 70m (making up numbers) may be true close to the equator but false at the tip of south america. Haven't actually looked at if that is how you're calculating, but it could explain the changes in overlap

**Comment by RedSparr0w** [comment]
``` javascript
var bounds = $scope.rectangle.getBounds();
var i=0;
for (nextS = bounds.f.b; (nextS + (180/Math.PI)*(105/6378137)) > bounds.f.f; nextS -= (180/Math.PI)*(105/6378137)){
    nextEE = bounds.b.b;
    if (++i % 2 == 0){
        nextEE += (180/Math.PI)*(80/6378137)
    }
    for (nextE = nextEE; (nextE - (180/Math.PI)*(80/6378137)) < bounds.b.f; nextE += (180/Math.PI)*(160/6378137)){
        $scope.addNewMarker(nextS,nextE,Index);
    }
}
```

basically 
next position East: `nextE += (180/Math.PI)*(160/6378137)`
next position South: `nextS -= (180/Math.PI)*(105/6378137)`

**Comment by bunzosteele** [comment]
So I've pulled your fork and played around with it a bit, other than the few display bugs for the tweet content section, it seems to be working really well and is insanely cool. Unfortunately, I really don't think I can comfortably merge this in while the PokemonGo/Twitter account info is being sent off to a script that is hosted elsewhere and not included in the PR. I know it would be messy, but would it be possible to just include the script on the page?

**Comment by RedSparr0w** [comment]
None of the information gets sent anywhere from the local disk.

The only place it is stored is the browsers [localStorage](http://www.w3schools.com/html/html5_webstorage.asp).

The scripts that are used are:
- [Google maps api v3](https://developers.google.com/maps/documentation/javascript/tutorial)
- [jQuery](https://jquery.com/)
- [AngularJS](https://angularjs.org/)
- [SweetAlert](http://t4t5.github.io/sweetalert/)
- [Materialize](http://materializecss.com/)

which no information gets sent to any of these.

Although we could replace SweetAlert with [Materialize Toast](http://materializecss.com/dialogs.html) to lower the dependencies

But if you want they could all be included locally? (other than google maps api)

**Comment by RedSparr0w** [comment]
Added total scan time: (based on 5 seconds per marker)


Fixed the display bug in the twitter section
Removed console logging
Changed `$scope.$apply` --> `try{$scope.$apply();}catch(err){}` as to avoid errors when nothing has changed

**Comment by bunzosteele** [comment]
I guess I just wasn't seeing where the data was being referenced and assumed it was an external script. I'll take a closer ook

**Comment by bunzosteele** [comment]
Okay, I see how it is engaging with LocalStorage

**Comment by bunzosteele** [comment]
Just got a message from /u/kyriten:

>    I saw that you have already moved to another ConfigGenerator (which looks really cool btw), but I wanted to offer an upgraded version of the LocationsGenerator.html included in PokeWatch V3.
> The changes include: \* added the ability to remove placed markers \* added a visual scanned area around each placed marker \* added a clear all markers option \* added the ability to drag and drop to move an already placed marker
> Here is a link to code: `http://pastebin.com/sNM36TPp`
> Feel free to use, post, share, ignore, etc. And thanks for everything your doing!

Seems like a few features that are missing but planned for the config generator, figured I'd share in case you can swipe/reuse it to save some time.

**Pull request merged**
